from pathlib import Path
from fastapi.testclient import TestClient
from legal.matter.settlement_scenarios import SettlementScenarioStore
from nh_family_law_llm import api as api_module
def rows():return [{"evidence_id":"PROPOSAL-001","source_hash":"a"*64,"title":"Fictional proposal"}]
def payload():return {"comparison_id":"settlement_001","reviewer_safe_id":"reviewer_001","user_confirmed":True,"scenarios":[{"scenario_id":"scenario_a","label":"A","schedules":["Fictional schedule"],"property":[],"support":[],"implementation":[],"unresolved_terms":["Fictional unresolved term"],"source_ref":{"record_id":"PROPOSAL-001","source_hash":"a"*64}},{"scenario_id":"scenario_b","label":"B","schedules":[],"property":["Fictional property term"],"support":[],"implementation":[],"unresolved_terms":[],"source_ref":{"record_id":"PROPOSAL-001","source_hash":"a"*64}}]}
def test_pass97_encrypted_comparison_does_not_recommend(tmp_path:Path):
 root=tmp_path/'m';root.mkdir();s=SettlementScenarioStore(root,encryption_key='fictional-test-key');r=s.create(payload(),records=rows());assert r['recommendation']=='not_available' and 'schedules' in r['different_areas'];assert s.source('settlement_001','scenario_a')['source']['source_hash']=='a'*64;assert 'Fictional property term' not in s.path.read_text()
def test_pass97_api_scope_drilldown_and_ui(monkeypatch,tmp_path:Path):
 a,b=tmp_path/'a',tmp_path/'b';a.mkdir();b.mkdir();active={'root':a};monkeypatch.setattr(api_module,'active_case_root',lambda:active['root']);monkeypatch.setattr(api_module,'load_case_search_records',lambda _:rows());monkeypatch.setenv('NH_MATTER_STORE_KEY','fictional-test-key');c=TestClient(api_module.app);assert c.post('/api/settlement-scenario-comparisons',json=payload()).status_code==200;assert len(c.get('/api/settlement-scenario-comparisons/settlement_001/scenarios/scenario_a/source').json()['source']['source_token'])==64;active['root']=b;assert c.get('/api/settlement-scenario-comparisons/settlement_001').status_code==404;assert Path('src/nh_family_law_llm/api.py').read_bytes()==Path('nh_family_law_llm/api.py').read_bytes();assert 'Settlement scenario comparator' in Path('src/nh_family_law_llm/ui/workbench.js').read_text(encoding='utf-8')
