from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import zipfile
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET

EXPECTED_PACKAGE_NAME = "TAHAIWebServices.NHFamilyLawLLM"
EXPECTED_PUBLISHER = "CN=D75EE668-B409-45ED-87E5-E37AA5FE3868"
DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MSIX_PATH = DEFAULT_REPO_ROOT / "dist" / "release" / "v8.0.0" / "msix" / "NHFamilyLawLLM_8.0.0.0_x64.msix"
# The qualified candidate's package audits live alongside the candidate rather
# than in the long-retired generic ``dist/store`` location.  WACK is a
# qualification result generated by the Windows tooling and is intentionally
# kept separately so a missing result remains a visible release blocker.
DEFAULT_EVIDENCE_ROOT = DEFAULT_REPO_ROOT / "dist" / "release" / "v8.0.0" / "evidence"
DEFAULT_WACK_RESULT = DEFAULT_REPO_ROOT / "dist" / "ga_today" / "evidence" / "wack" / "wack-result.json"

APPX_NS = "http://schemas.microsoft.com/appx/manifest/foundation/windows10"
UAP_NS = "http://schemas.microsoft.com/appx/manifest/uap/windows10"
DESKTOP_NS = "http://schemas.microsoft.com/appx/manifest/desktop/windows10"
RESCAP_NS = "http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"

REQUIRED_TOP_LEVEL_FILES = {"AppxManifest.xml", "AppxBlockMap.xml", "[Content_Types].xml"}
REQUIRED_NOTICE_PATTERNS = ("license", "licenses/")
FORBIDDEN_EXACT_BASENAMES = {
    "store-preflight.json",
    "store-preflight.txt",
    "installed-offline-qualification.json",
    "installed-offline-qualification.txt",
    "private-data-audit.json",
    "bundled-engine-inventory.json",
    "msix-path-audit.json",
    "sealed-msix-payload.json",
    "sealed-msix-payload-audit.json",
    "sealed-msix-archive-audit.json",
    "msix-staging-manifest.json",
    "package-file-manifest.json",
    "runtime-dependency-probe.json",
    "store-build-smoke.json",
    "final-runtime-cleanup.json",
    "final-staging-cleanup.json",
    "bytecode-regeneration-trace.json",
    "test-summary.txt",
    "wack-result.json",
    "source_manifest.json",
    "private_search_index.json",
}
FORBIDDEN_PREFIXES = (
    "dist/",
    "build/",
    "out/",
    "temp/",
    "tmp/",
    "logs/",
    "log/",
    "tests/",
    "test/",
    "eval_data/",
    "store/evidence/",
    "case_",
    "matter_",
)
FORBIDDEN_SEGMENTS = {"__pycache__", ".pytest_cache", "tests"}


def utc_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def _canonical_path(name: str) -> str:
    return name.replace("\\", "/").lstrip("/")


def _parse_manifest(msix_path: Path) -> tuple[str, ET.Element]:
    with zipfile.ZipFile(msix_path) as archive:
        manifest_bytes = archive.read("AppxManifest.xml")
    manifest_text = manifest_bytes.decode("utf-8-sig")
    return manifest_text, ET.fromstring(manifest_text)


def _qname(namespace: str, local_name: str) -> str:
    return f"{{{namespace}}}{local_name}"


def _child_text(parent: ET.Element | None, namespace: str, local_name: str) -> str:
    if parent is None:
        return ""
    return (parent.findtext(_qname(namespace, local_name)) or "").strip()


def _find_sdk_tool(tool_name: str) -> str | None:
    kit_root = Path(r"C:\Program Files (x86)\Windows Kits\10\bin")
    if not kit_root.exists():
        return None
    candidates = sorted(
        (path for path in kit_root.rglob(tool_name) if "\\x64\\" in str(path).lower()),
        key=lambda path: str(path).lower(),
    )
    return str(candidates[0]) if candidates else None


def _parse_wack_result(wack_result_path: Path, *, candidate_msix_path: Path) -> dict[str, Any]:
    if not wack_result_path.exists():
        return {
            "status": "not_run",
            "reason": "wack_result_not_found",
            "package_path": str(candidate_msix_path),
            "package_sha256": "",
            "artifact_path": str(wack_result_path),
        }
    try:
        payload = _read_json(wack_result_path)
        if not isinstance(payload, dict):
            raise ValueError("invalid_wack_result")
    except (OSError, ValueError):
        return {
            "status": "blocked",
            "reason": "wack_result_unreadable",
            "package_path": str(candidate_msix_path),
            "package_sha256": "",
            "artifact_path": str(wack_result_path),
            "validation_issues": ["result_unreadable"],
        }
    status = str(payload.get("status") or "not_run")
    package = payload.get("package") if isinstance(payload.get("package"), dict) else {}
    report = payload.get("report") if isinstance(payload.get("report"), dict) else {}
    issues: list[str] = []
    if payload.get("blockers") or payload.get("store_release_blocked"):
        issues.append("qualification_blockers_present")
    if report.get("failures") or report.get("failure_count") or report.get("parser_error"):
        issues.append("report_failed")
    if status == "pass":
        if payload.get("execution_status") not in {"completed", "pass"}:
            issues.append("execution_not_completed")
        if report.get("failure_count") != 0 or not report.get("sha256"):
            issues.append("report_evidence_missing")
        if type(report.get("passed_test_count")) is not int or report["passed_test_count"] < 1:
            issues.append("explicit_passed_tests_missing")
    if payload.get("package_sha256") and package.get("sha256"):
        if str(payload["package_sha256"]).lower() != str(package["sha256"]).lower():
            issues.append("conflicting_package_hashes")
    return {
        "status": status,
        "reason": payload.get("reason") or payload.get("detail") or "",
        # The WACK parser records a package hash, but older blocked reports do
        # not contain a path.  Never backfill that omission with a historic
        # release default: bind the report to the candidate under review and
        # surface an absent hash as an unverifiable WACK result.
        "package_path": payload.get("package_path") or str(candidate_msix_path),
        "package_sha256": str(payload.get("package_sha256") or package.get("sha256") or ""),
        "artifact_path": str(wack_result_path),
        "validation_issues": issues,
    }


def audit_manifest(msix_path: Path, expected_version: str) -> dict[str, Any]:
    manifest_text, root = _parse_manifest(msix_path)
    ns = {"a": APPX_NS, "uap": UAP_NS, "desktop": DESKTOP_NS, "rescap": RESCAP_NS}
    identity = root.find("a:Identity", ns)
    properties = root.find("a:Properties", ns)
    resources = root.find("a:Resources", ns)
    application = root.find("a:Applications/a:Application", ns)
    visual_elements = root.find("a:Applications/a:Application/uap:VisualElements", ns)
    default_tile = root.find("a:Applications/a:Application/uap:VisualElements/uap:DefaultTile", ns)
    splash_screen = root.find("a:Applications/a:Application/uap:VisualElements/uap:SplashScreen", ns)
    dependencies = root.findall("a:Dependencies/*", ns)
    capabilities = root.findall("a:Capabilities/*", ns)
    extension_nodes = root.findall("a:Applications/a:Application/a:Extensions/*", ns)

    issues: list[str] = []
    if identity is None:
        issues.append("missing_identity")
    else:
        identity_name = identity.attrib.get("Name", "")
        identity_publisher = identity.attrib.get("Publisher", "")
        identity_version = identity.attrib.get("Version", "")
        architecture = identity.attrib.get("ProcessorArchitecture", "")
        if identity_name != EXPECTED_PACKAGE_NAME:
            issues.append("identity_name_mismatch")
        if identity_publisher != EXPECTED_PUBLISHER:
            issues.append("publisher_mismatch")
        if identity_version != expected_version:
            issues.append("version_mismatch")
        if architecture.lower() != "x64":
            issues.append("processor_architecture_mismatch")
    if properties is None:
        issues.append("missing_properties")
    else:
        display_name = _child_text(properties, APPX_NS, "DisplayName")
        description = _child_text(properties, APPX_NS, "Description")
        if not display_name:
            issues.append("missing_display_name")
        if not description:
            issues.append("missing_description")
    if resources is None or not any((resource.attrib.get("Language") or "").lower() == "en-us" for resource in resources):
        issues.append("missing_en_us_resource")
    if application is None:
        issues.append("missing_application")
    else:
        if application.attrib.get("Executable") != "NHFamilyLawLLM.exe":
            issues.append("executable_mismatch")
        if application.attrib.get("EntryPoint") != "Windows.FullTrustApplication":
            issues.append("entry_point_mismatch")
    if visual_elements is None:
        issues.append("missing_visual_elements")
    else:
        for asset in ("Square150x150Logo", "Square44x44Logo"):
            if not visual_elements.attrib.get(asset):
                issues.append(f"missing_visual_asset:{asset}")
        if default_tile is None:
            issues.append("missing_default_tile")
        else:
            for asset in ("Wide310x150Logo", "Square310x310Logo"):
                if not default_tile.attrib.get(asset):
                    issues.append(f"missing_visual_asset:{asset}")
        if splash_screen is None or not splash_screen.attrib.get("Image"):
            issues.append("missing_visual_asset:Image")
        if not (visual_elements.attrib.get("DisplayName") or "").strip():
            issues.append("missing_visual_display_name")
        if not (visual_elements.attrib.get("Description") or "").strip():
            issues.append("missing_visual_description")
    if not dependencies:
        issues.append("missing_target_device_family")
    else:
        allowed_dependencies = {
            ("Windows.Desktop", "10.0.19041.0", "10.0.26100.0"),
        }
        dep_key = tuple(dependencies[0].attrib.get(key, "") for key in ("Name", "MinVersion", "MaxVersionTested"))
        if dep_key not in allowed_dependencies:
            issues.append("target_device_family_mismatch")
    capability_names = [node.attrib.get("Name", "") for node in capabilities]
    if capability_names != ["runFullTrust"]:
        issues.append("capability_mismatch")
    if extension_nodes:
        # The package deliberately has two supported extensions: the full-trust
        # desktop process and the view-only ``nhfl`` protocol.  Treating the
        # required uap protocol extension as unsupported made every real
        # package fail preflight even when its manifest was valid.
        desktop_extensions = [
            node for node in extension_nodes if node.tag == _qname(DESKTOP_NS, "Extension")
        ]
        protocol_extensions = [
            node for node in extension_nodes if node.tag == _qname(UAP_NS, "Extension")
        ]
        if len(desktop_extensions) != 1 or len(protocol_extensions) != 1 or len(extension_nodes) != 2:
            issues.append("unsupported_extension_namespace")
        for node in desktop_extensions:
            if (
                node.attrib.get("Category") != "windows.fullTrustProcess"
                or node.attrib.get("Executable") != "NHFamilyLawLLM.exe"
            ):
                issues.append("unsupported_extension_category")
        for node in protocol_extensions:
            protocol = node.find(_qname(UAP_NS, "Protocol"))
            if (
                node.attrib.get("Category") != "windows.protocol"
                or node.attrib.get("Executable") != "NHFamilyLawLLM.exe"
                or node.attrib.get("EntryPoint") != "Windows.FullTrustApplication"
                or protocol is None
                or protocol.attrib.get("Name") != "nhfl"
            ):
                issues.append("unsupported_extension_category")
    if "x-generate" in manifest_text.lower():
        issues.append("x_generate_present")

    return {
        "status": "pass" if not issues else "fail",
        "issues": issues,
        "identity": identity.attrib if identity is not None else {},
        "properties": {
            "display_name": _child_text(properties, APPX_NS, "DisplayName"),
            "publisher_display_name": _child_text(properties, APPX_NS, "PublisherDisplayName"),
            "description": _child_text(properties, APPX_NS, "Description"),
        },
        "resources": [resource.attrib for resource in resources] if resources is not None else [],
        "application": application.attrib if application is not None else {},
        "visual_elements": visual_elements.attrib if visual_elements is not None else {},
        "default_tile": default_tile.attrib if default_tile is not None else {},
        "splash_screen": splash_screen.attrib if splash_screen is not None else {},
        "dependencies": [node.attrib for node in dependencies],
        "capabilities": capability_names,
        "extensions": [node.attrib for node in extension_nodes],
    }


def audit_archive(msix_path: Path) -> dict[str, Any]:
    issues: list[str] = []
    with zipfile.ZipFile(msix_path) as archive:
        raw_names = [info.filename for info in archive.infolist() if not info.is_dir()]
        names = [_canonical_path(name) for name in raw_names]
        normalized = [name.lower() for name in names]
        duplicate_counts = Counter(normalized)
        duplicate_paths = sorted(path for path, count in duplicate_counts.items() if count > 1)
        if duplicate_paths:
            issues.append("duplicate_destination_path")
        traversal_hits = [name for name in raw_names if name.startswith("/") or name.startswith("\\") or ".." in Path(name).parts or ":" in name]
        if traversal_hits:
            issues.append("path_traversal_or_ads")
        required_missing = sorted(path for path in REQUIRED_TOP_LEVEL_FILES if path not in names)
        if required_missing:
            issues.append("missing_required_package_files")
        notice_hits = [name for name in names if any(pattern in name.lower() for pattern in REQUIRED_NOTICE_PATTERNS)]
        if not notice_hits:
            issues.append("third_party_notices_missing")

        forbidden_hits = []
        for name in names:
            lower = name.lower()
            basename = Path(name).name.lower()
            if any(lower.startswith(prefix) for prefix in FORBIDDEN_PREFIXES):
                forbidden_hits.append(name)
                continue
            if basename in FORBIDDEN_EXACT_BASENAMES:
                forbidden_hits.append(name)
                continue
            if any(segment in FORBIDDEN_SEGMENTS for segment in Path(name).parts):
                forbidden_hits.append(name)
                continue
        if forbidden_hits:
            issues.append("forbidden_package_entries")

        # Partner Center signs MSIX submissions. Unsigned is not sideload-ready,
        # but must not create a fictitious certificate requirement for upload.
        # https://learn.microsoft.com/en-us/windows/msix/package/sign-msix-package-guide
        signature_present = "appxsignature.p7x" in normalized
        signature_state = "unsigned_store_signing_pending"
        signature_tool = _find_sdk_tool("signtool.exe") if signature_present else None
        signature_details = {"tool_path": signature_tool or "", "exit_code": None, "stdout": "", "stderr": ""}
        if signature_present and signature_tool:
            completed = subprocess.run(
                [signature_tool, "verify", "/pa", "/v", str(msix_path)],
                capture_output=True,
                text=True,
                check=False,
            )
            signature_details.update(
                {
                    "exit_code": completed.returncode,
                    "stdout": completed.stdout,
                    "stderr": completed.stderr,
                }
            )
            if completed.returncode == 0:
                signature_state = "signed_verified"
            elif "not trusted" in f"{completed.stdout}\n{completed.stderr}".lower():
                signature_state = "signed_untrusted_chain"
                issues.append("signature_verification_failed")
            else:
                signature_state = "verify_failed"
                issues.append("signature_verification_failed")
        elif signature_present:
            signature_state = "signtool_not_found"
            issues.append("signtool_not_found")

    return {
        "status": "pass" if not issues else "fail",
        "issues": issues,
        "signature_state": signature_state,
        "signature_details": signature_details,
        "signing_scope": "microsoft_store_submission_not_sideload_installation",
        "duplicate_destination_paths": duplicate_paths,
        "traversal_hits": traversal_hits,
        "required_missing": required_missing,
        "notice_hits": notice_hits,
        "forbidden_hits": forbidden_hits,
        "required_top_level_files": sorted(REQUIRED_TOP_LEVEL_FILES),
        "entry_count": len(names),
    }


def audit_evidence(repo_root: Path, msix_path: Path, evidence_root: Path) -> dict[str, Any]:
    evidence_paths = {
        "bundled_engine_inventory": evidence_root / "bundled-engine-inventory.json",
        "private_data_audit": evidence_root / "private-data-audit.json",
        "installed_offline_qualification": evidence_root / "installed-offline-qualification.json",
        "sealed_msix_payload": evidence_root / "sealed-msix-payload.json",
        "sealed_msix_payload_audit": evidence_root / "sealed-msix-payload-audit.json",
        "sealed_msix_archive_audit": evidence_root / "sealed-msix-archive-audit.json",
        "msix_path_audit": evidence_root / "msix-path-audit.json",
        "package_file_manifest": evidence_root / "package-file-manifest.json",
        "store_build_smoke": evidence_root / "store-build-smoke.json",
    }
    statuses: dict[str, Any] = {}
    issues: list[str] = []
    payloads: dict[str, Any] = {}
    for name, path in evidence_paths.items():
        if not path.exists():
            statuses[name] = {"status": "missing", "path": str(path)}
            issues.append(f"missing_{name}")
            payloads[name] = {}
            continue
        payload = _read_json(path)
        payloads[name] = payload
        if isinstance(payload, list):
            statuses[name] = {
                "status": "present",
                "generated_at": None,
                "path": str(path),
                "entry_count": len(payload),
            }
            continue
        statuses[name] = {
            "status": payload.get("status") or payload.get("qualification_status") or "unknown",
            "generated_at": payload.get("generated_at"),
            "path": str(path),
        }
    # Missing qualification artifacts are release blockers, not an exception
    # from the checker.  Preserve the per-artifact missing status above and
    # complete the report with a fail-closed evidence audit.
    inventory = payloads["bundled_engine_inventory"] if isinstance(payloads["bundled_engine_inventory"], dict) else {}
    private_audit = payloads["private_data_audit"] if isinstance(payloads["private_data_audit"], dict) else {}
    installed_offline = payloads["installed_offline_qualification"] if isinstance(payloads["installed_offline_qualification"], dict) else {}
    archive_audit = payloads["sealed_msix_archive_audit"] if isinstance(payloads["sealed_msix_archive_audit"], dict) else {}
    payload_audit = payloads["sealed_msix_payload_audit"] if isinstance(payloads["sealed_msix_payload_audit"], dict) else {}
    package_file_manifest = payloads["package_file_manifest"] if isinstance(payloads["package_file_manifest"], list) else []
    msix_path_audit = payloads["msix_path_audit"] if isinstance(payloads["msix_path_audit"], dict) else {}

    if inventory.get("status") != "pass" or inventory.get("failures"):
        issues.append("bundled_engine_inventory_failed")
    if private_audit.get("status") != "pass":
        issues.append("private_data_audit_failed")
    if installed_offline.get("qualification_status") != "pass" or installed_offline.get("blockers"):
        issues.append("installed_offline_qualification_failed")
    if payload_audit.get("status") != "pass":
        issues.append("sealed_msix_payload_audit_failed")
    if archive_audit.get("status") != "pass":
        issues.append("sealed_msix_archive_audit_failed")
    if msix_path_audit and msix_path_audit.get("status") != "pass":
        issues.append("msix_path_audit_failed")
    if not package_file_manifest:
        issues.append("package_file_manifest_missing")
    if archive_audit.get("msix_path") and Path(str(archive_audit["msix_path"])) != msix_path:
        issues.append("archive_audit_package_path_mismatch")
    if installed_offline.get("files", {}).get("installed_offline_qualification_json"):
        if Path(installed_offline["files"]["installed_offline_qualification_json"]) != evidence_paths["installed_offline_qualification"]:
            issues.append("installed_offline_qualification_path_mismatch")

    return {
        "status": "pass" if not issues else "fail",
        "issues": issues,
        "package_file_manifest_count": len(package_file_manifest),
        "evidence_files": statuses,
        "bundled_engine_inventory": {
            "status": inventory.get("status"),
            "package_count": inventory.get("package_count"),
            "failures": inventory.get("failures") or [],
        },
        "private_data_audit": {
            "status": private_audit.get("status"),
            "blocked_paths": private_audit.get("blocked_paths") or [],
            "blocked_files": private_audit.get("blocked_files") or [],
        },
        "installed_offline_qualification": {
            "status": installed_offline.get("qualification_status"),
            "blockers": installed_offline.get("blockers") or [],
        },
        "sealed_msix_payload_audit": {
            "status": payload_audit.get("status"),
        },
        "sealed_msix_archive_audit": {
            "status": archive_audit.get("status"),
            "msix_path": archive_audit.get("msix_path"),
        },
        "msix_path_audit": msix_path_audit,
    }


def build_preflight_report(repo_root: Path, msix_path: Path, evidence_root: Path, wack_result_path: Path) -> dict[str, Any]:
    identity_spec = _read_json(repo_root / "store" / "msix" / "identity.example.json")
    package_sha256 = sha256_file(msix_path)
    manifest_audit = audit_manifest(msix_path, str(identity_spec.get("package_version") or ""))
    archive_audit = audit_archive(msix_path)
    evidence_audit = audit_evidence(repo_root, msix_path, evidence_root)
    wack_result = _parse_wack_result(wack_result_path, candidate_msix_path=msix_path)

    manifest_ok = manifest_audit["status"] == "pass"
    archive_ok = archive_audit["status"] == "pass"
    evidence_ok = evidence_audit["status"] == "pass"
    # Execution completing is not the same as certification passing. All
    # qualification and identity blockers must be known before deciding ready.
    wack_ok = wack_result["status"] == "pass"

    blockers: list[str] = []
    if not manifest_ok:
        blockers.extend(f"manifest:{issue}" for issue in manifest_audit["issues"])
    if not archive_ok:
        blockers.extend(f"archive:{issue}" for issue in archive_audit["issues"])
    if not evidence_ok:
        blockers.extend(f"evidence:{issue}" for issue in evidence_audit["issues"])
    if not wack_ok:
        blockers.append(f"wack:{wack_result['status']}")
        if wack_result.get("reason"):
            blockers.append(f"wack_reason:{wack_result['reason']}")
    blockers.extend(f"wack:{issue}" for issue in wack_result.get("validation_issues", []))
    wack_hash = str(wack_result.get("package_sha256") or "").lower()
    if not wack_hash:
        blockers.append("wack:package_hash_missing")
    elif wack_hash != package_sha256.lower():
        blockers.append("wack:package_hash_mismatch")
    if Path(str(wack_result["package_path"])).resolve() != msix_path.resolve():
        blockers.append("wack:package_path_mismatch")
    final_readiness_state = (
        "READY_FOR_PARTNER_CENTER_UPLOAD"
        if manifest_ok and archive_ok and evidence_ok and wack_ok and not blockers
        else "BLOCKED"
    )

    return {
        "schema_version": "store_preflight_v1",
        "generated_at": utc_now(),
        "package": {
            "path": str(msix_path),
            "sha256": package_sha256,
            "size_bytes": msix_path.stat().st_size,
        },
        "expected_identity": identity_spec,
        "manifest_audit": manifest_audit,
        "content_audit": archive_audit,
        "evidence_audit": evidence_audit,
        "wack": wack_result,
        "final_readiness_state": final_readiness_state,
        "blockers": blockers,
        "package_hash_tied_evidence": {
            "msix_path_audit": str(evidence_root / "msix-path-audit.json"),
            "sealed_msix_archive_audit": str(evidence_root / "sealed-msix-archive-audit.json"),
            "sealed_msix_payload_audit": str(evidence_root / "sealed-msix-payload-audit.json"),
            "installed_offline_qualification": str(evidence_root / "installed-offline-qualification.json"),
            "private_data_audit": str(evidence_root / "private-data-audit.json"),
            "bundled_engine_inventory": str(evidence_root / "bundled-engine-inventory.json"),
        },
    }


def write_outputs(report: dict[str, Any], json_path: Path, txt_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    lines = [
        f"Package: {report['package']['path']}",
        f"Package SHA-256: {report['package']['sha256']}",
        f"Package identity: {report['manifest_audit']['identity'].get('Name', '')}",
        f"Manifest audit: {report['manifest_audit']['status']}",
        f"Content audit: {report['content_audit']['status']}",
        f"Evidence audit: {report['evidence_audit']['status']}",
        f"Bundled engine inventory: {report['evidence_audit']['bundled_engine_inventory']['status']}",
        f"Private-data audit: {report['evidence_audit']['private_data_audit']['status']}",
        f"Installed-offline qualification: {report['evidence_audit']['installed_offline_qualification']['status']}",
        f"WACK: {report['wack']['status']}",
        f"Final readiness: {report['final_readiness_state']}",
    ]
    if report["wack"].get("reason"):
        lines.append(f"WACK reason: {report['wack']['reason']}")
    if report["blockers"]:
        lines.append("Blockers:")
        lines.extend(f"- {blocker}" for blocker in report["blockers"])
    txt_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the Store package-compliance preflight slice.")
    parser.add_argument("--repo-root", default=str(DEFAULT_REPO_ROOT))
    parser.add_argument("--msix-path", default=str(DEFAULT_MSIX_PATH))
    parser.add_argument("--evidence-root", default=str(DEFAULT_EVIDENCE_ROOT))
    parser.add_argument("--wack-result", default=str(DEFAULT_WACK_RESULT))
    parser.add_argument("--output-json", default="")
    parser.add_argument("--output-txt", default="")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    msix_path = Path(args.msix_path).resolve()
    evidence_root = Path(args.evidence_root).resolve()
    wack_result = Path(args.wack_result).resolve()
    output_json = Path(args.output_json).resolve() if args.output_json else evidence_root / "store-preflight.json"
    output_txt = Path(args.output_txt).resolve() if args.output_txt else evidence_root / "store-preflight.txt"

    report = build_preflight_report(repo_root, msix_path, evidence_root, wack_result)
    write_outputs(report, output_json, output_txt)
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
