from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app.web.ui_inventory import REQUIRED_UI_VIEWS

REQUIRED_UI_MARKERS = {
    "source_card": "data-source-card",
    "claim_drilldown": "data-claim-drilldown",
    "citation_drilldown": "data-citation-drilldown",
    "source_text_drilldown": "data-source-text-drilldown",
    "verifier_result_drilldown": "data-verifier-result-drilldown",
    "review_status": "data-review-status",
    "blocked_export_explanation": "data-blocked-export-explanation",
    "provider_connection_card": "data-provider-connection-card",
    "provider_status_card": "data-provider-status-card",
    "outbound_manifest": "data-outbound-manifest",
    "sharing_summary": "data-sharing-summary",
    "exact_outbound_preview": "data-exact-outbound-preview",
    "redactions": "data-redactions",
    "approval": "data-approval",
    "live_timeline": "data-live-timeline",
    "participation": "data-participation",
    "failures": "data-failures",
    "budgets": "data-budgets",
    "final_verified_synthesis": "data-final-verified-synthesis",
    "privacy_controls": "data-privacy-controls",
    "security_controls": "data-security-controls",
    "matter_encryption": "data-matter-encryption",
    "audit_integrity": "data-audit-integrity",
    "backup_restore": "data-backup-restore",
    "retention_controls": "data-retention-controls",
    "incident_controls": "data-incident-controls",
    "injection_defense": "data-injection-defense",
    "release_control_center": "data-release-control-center",
    "release_observability": "data-release-observability",
    "release_accessibility": "data-release-accessibility",
    "release_supply_chain": "data-release-supply-chain",
    "release_vulnerability_evidence": "data-release-vulnerability-evidence",
    "release_msix_audit": "data-release-msix-audit",
    "release_red_team": "data-release-red-team",
    "release_metrics_gates": "data-release-metrics-gates",
    "release_pilot_evidence": "data-release-pilot-evidence",
    "release_blockers": "data-release-blockers",
    "release_maintenance_center": "data-release-maintenance-center",
    "release_pilot_hardening": "data-release-pilot-hardening",
    "attorney_sandbox_operations": "data-attorney-sandbox-operations",
    "limited_real_matter_pilot": "data-limited-real-matter-pilot",
    "ga_release_candidate": "data-ga-release-candidate",
    "ga_shipment_readiness": "data-ga-shipment-readiness",
    "feedback_loop": "data-feedback-loop",
    "support_bundle": "data-support-bundle",
    "child_profile": "data-child-profile",
    "child_safe_alias": "data-child-safe-alias",
    "child_masking": "data-child-masking",
    "health_care": "data-health-care",
    "school_records": "data-school-records",
    "care_records": "data-care-records",
    "service_records": "data-service-records",
    "routine_records": "data-routine-records",
    "transportation_records": "data-transportation-records",
    "contact_records": "data-contact-records",
    "appointment_ledger": "data-appointment-ledger",
    "schedule_scenarios": "data-schedule-scenarios",
    "neutral_schedule": "data-neutral-schedule",
    "continuity_gaps": "data-continuity-gaps",
    "claims_contradictions": "data-claims-contradictions",
    "privacy_review": "data-privacy-review",
    "review_history": "data-review-history",
    "child_focused_packet": "data-child-focused-packet",
    "communications_workbench": "data-communications-workbench",
    "hearing_media_workbench": "data-hearing-media-workbench",
    "thread_reconstruction": "data-thread-reconstruction",
    "schedule_history": "data-schedule-history",
    "parenting_time_review": "data-parenting-time-review",
    "agreement_mapping": "data-agreement-mapping",
    "completeness": "data-completeness",
    "export_receipt": "data-export-receipt",
    "media_inventory": "data-media-inventory",
    "transcript_viewer": "data-transcript-viewer",
    "speaker_review": "data-speaker-review",
    "hearing_timeline": "data-hearing-timeline",
    "transcript_comparison": "data-transcript-comparison",
    "exhibit_references": "data-exhibit-references",
    "appellate_record_completeness": "data-appellate-record-completeness",
    "record_citations": "data-record-citations",
    "privacy_redaction": "data-privacy-redaction",
    "attorney_eval_lab": "data-attorney-eval-lab",
    "eval_export_bundle": "data-eval-export-bundle",
    "governance_control_registry": "data-governance-control-registry",
    "framework_mappings": "data-framework-mappings",
    "policy_library": "data-policy-library",
    "policy_packs": "data-policy-packs",
    "model_cards": "data-model-cards",
    "data_cards": "data-data-cards",
    "vendor_risks": "data-vendor-risks",
    "exceptions": "data-exceptions",
    "sign_offs": "data-sign-offs",
    "diligence_packet": "data-diligence-packet",
    "gaps_remediation": "data-gaps-remediation",
    "governance_history": "data-governance-history",
    "local_intelligence_control_center": "data-local-intelligence-control-center",
    "hardware_profile": "data-hardware-profile",
    "model_registry": "data-model-registry",
    "role_permissions": "data-role-permissions",
    "benchmark_runner": "data-benchmark-runner",
    "routing_fallbacks": "data-routing-fallbacks",
    "health_failures": "data-health-failures",
    "storage_cache": "data-storage-cache",
    "quarantine_removal": "data-quarantine-removal",
    "degraded_modes": "data-degraded-modes",
    "admission_history": "data-admission-history",
}

VIEW_SPECIFIC_MARKERS = {
    "ask.tsx": ["source_card", "claim_drilldown", "citation_drilldown", "source_text_drilldown", "verifier_result_drilldown"],
    "draft-workspace.tsx": ["review_status", "source_card", "blocked_export_explanation"],
    "filing-ready.tsx": ["review_status", "blocked_export_explanation", "verifier_result_drilldown"],
    "citation-report.tsx": ["citation_drilldown", "source_card", "verifier_result_drilldown"],
    "quote-report.tsx": ["source_text_drilldown", "verifier_result_drilldown"],
    "source-library.tsx": ["source_card", "source_text_drilldown"],
    "authority-matrix.tsx": ["source_card", "citation_drilldown"],
    "human-review-queue.tsx": ["review_status"],
    "admin-eval-dashboard.tsx": [
        "review_status",
        "blocked_export_explanation",
        "source_card",
        "claim_drilldown",
        "citation_drilldown",
        "source_text_drilldown",
        "verifier_result_drilldown",
        "attorney_eval_lab",
        "eval_export_bundle",
    ],
    "connections-deliberation.tsx": [
        "review_status",
        "provider_connection_card",
        "provider_status_card",
        "outbound_manifest",
        "exact_outbound_preview",
        "redactions",
        "approval",
        "live_timeline",
        "participation",
        "failures",
        "budgets",
        "final_verified_synthesis",
        "sharing_summary",
        "privacy_controls",
    ],
    "security-privacy-center.tsx": [
        "review_status",
        "security_controls",
        "matter_encryption",
        "audit_integrity",
        "backup_restore",
        "retention_controls",
        "incident_controls",
        "injection_defense",
        "blocked_export_explanation",
    ],
    "release-control-center.tsx": [
        "review_status",
        "release_control_center",
        "release_observability",
        "release_accessibility",
        "release_supply_chain",
        "release_vulnerability_evidence",
        "release_msix_audit",
        "release_red_team",
        "release_metrics_gates",
        "release_pilot_evidence",
        "release_blockers",
        "blocked_export_explanation",
    ],
    "maintenance-center.tsx": [
        "review_status",
        "release_maintenance_center",
        "release_pilot_hardening",
        "attorney_sandbox_operations",
        "limited_real_matter_pilot",
        "ga_release_candidate",
        "ga_shipment_readiness",
        "feedback_loop",
        "support_bundle",
    ],
    "child-continuity.tsx": [
        "review_status",
        "child_profile",
        "child_safe_alias",
        "child_masking",
        "health_care",
        "school_records",
        "care_records",
        "service_records",
        "routine_records",
        "transportation_records",
        "contact_records",
        "appointment_ledger",
        "schedule_scenarios",
        "neutral_schedule",
        "continuity_gaps",
        "claims_contradictions",
        "privacy_review",
        "review_history",
        "child_focused_packet",
    ],
    "communications-parenting-time.tsx": [
        "review_status",
        "communications_workbench",
        "thread_reconstruction",
        "schedule_history",
        "parenting_time_review",
        "agreement_mapping",
        "completeness",
        "export_receipt",
        "privacy_review",
        "review_history",
    ],
    "hearing-media-workbench.tsx": [
        "review_status",
        "hearing_media_workbench",
        "media_inventory",
        "transcript_viewer",
        "speaker_review",
        "hearing_timeline",
        "transcript_comparison",
        "exhibit_references",
        "appellate_record_completeness",
        "record_citations",
        "privacy_redaction",
        "review_history",
        "export_receipt",
    ],
    "governance-policy-center.tsx": [
        "review_status",
        "governance_control_registry",
        "framework_mappings",
        "policy_library",
        "policy_packs",
        "model_cards",
        "data_cards",
        "vendor_risks",
        "exceptions",
        "sign_offs",
        "diligence_packet",
        "gaps_remediation",
        "governance_history",
        "blocked_export_explanation",
    ],
    "local-intelligence-control-center.tsx": [
        "review_status",
        "local_intelligence_control_center",
        "hardware_profile",
        "model_registry",
        "role_permissions",
        "benchmark_runner",
        "routing_fallbacks",
        "health_failures",
        "storage_cache",
        "quarantine_removal",
        "degraded_modes",
        "admission_history",
    ],
}


@dataclass
class UICompletionReport:
    status: str
    required_view_count: int
    missing_views: list[str]
    missing_markers: dict[str, list[str]]
    drilldown_chain_required: list[str]

    def as_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "required_view_count": self.required_view_count,
            "missing_views": self.missing_views,
            "missing_markers": self.missing_markers,
            "drilldown_chain_required": self.drilldown_chain_required,
        }


class UICompletionAuditor:
    def __init__(self, pages_dir: str | Path = "app/web/pages") -> None:
        self.pages_dir = Path(pages_dir)

    def audit(self) -> UICompletionReport:
        missing_views: list[str] = []
        missing_markers: dict[str, list[str]] = {}
        for view in REQUIRED_UI_VIEWS:
            path = self.pages_dir / view.file
            if not path.exists():
                missing_views.append(view.file)
                continue
            text = path.read_text(encoding="utf-8")
            required = VIEW_SPECIFIC_MARKERS.get(view.file, ["review_status"])
            absent = [marker_key for marker_key in required if REQUIRED_UI_MARKERS[marker_key] not in text]
            if absent:
                missing_markers[view.file] = absent
        status = "pass" if not missing_views and not missing_markers else "fail"
        return UICompletionReport(
            status=status,
            required_view_count=len(REQUIRED_UI_VIEWS),
            missing_views=missing_views,
            missing_markers=missing_markers,
            drilldown_chain_required=[
                "answer",
                "claim",
                "citation",
                "source_text",
                "verifier_result",
            ],
        )
